# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F3FBF4
background         #181A1A
cursor             #F3FBF4

active_tab_foreground     #181A1A
active_tab_background     #F3FBF4
inactive_tab_foreground   #F3FBF4
inactive_tab_background   #181A1A

active_border_color   #F3FBF4
inactive_border_color #181A1A
bell_border_color     #282F2D

color0      #3F4141
color1		#282F2D
color2		#414A46
color3		#5A655E
color4		#748077
color5		#8D9B90
color6		#A6B6A8
color7		#E6F1E7
color8		#A1A8A2
color9		#353F3D
color10		#57635D
color11		#78877E
color12		#9AAB9F
color13		#BCCFBF
color14		#DEF3E0
color15		#E6F1E7
