# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F9F9F9
background         #161616
cursor             #F9F9F9

active_tab_foreground     #161616
active_tab_background     #F9F9F9
inactive_tab_foreground   #F9F9F9
inactive_tab_background   #161616

active_border_color   #F9F9F9
inactive_border_color #161616
bell_border_color     #424242

color0      #3D3D3D
color1		#424242
color2		#4D4D4D
color3		#4E4E4E
color4		#767676
color5		#B3B3B3
color6		#B3B3B3
color7		#EEEEEE
color8		#A7A7A7
color9		#585858
color10		#676767
color11		#676767
color12		#9D9D9D
color13		#EEEEEE
color14		#EEEEEE
color15		#EEEEEE
