# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(181A1A)
$foreground = rgb(F3FBF4)
$color0 = rgb(3F4141)
$color1 = rgb(282F2D)
$color2 = rgb(414A46)
$color3 = rgb(5A655E)
$color4 = rgb(748077)
$color5 = rgb(8D9B90)
$color6 = rgb(A6B6A8)
$color7 = rgb(E6F1E7)
$color8 = rgb(A1A8A2)
$color9 = rgb(353F3D)
$color10 = rgb(57635D)
$color11 = rgb(78877E)
$color12 = rgb(9AAB9F)
$color13 = rgb(BCCFBF)
$color14 = rgb(DEF3E0)
$color15 = rgb(E6F1E7)
