# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161616)
$foreground = rgb(F9F9F9)
$color0 = rgb(3D3D3D)
$color1 = rgb(424242)
$color2 = rgb(4D4D4D)
$color3 = rgb(4E4E4E)
$color4 = rgb(767676)
$color5 = rgb(B3B3B3)
$color6 = rgb(B3B3B3)
$color7 = rgb(EEEEEE)
$color8 = rgb(A7A7A7)
$color9 = rgb(585858)
$color10 = rgb(676767)
$color11 = rgb(676767)
$color12 = rgb(9D9D9D)
$color13 = rgb(EEEEEE)
$color14 = rgb(EEEEEE)
$color15 = rgb(EEEEEE)
